all: Q1 Q1CommandLine Q2 Q3 Q4 Q5

Q1: Q1cpProg.c
	gcc -o Q1 Q1cpProg.c

Q1CommandLine: Q1cpProgCommandLineInput.c
	gcc -o Q1CommandLine Q1cpProgCommandLineInput.c

Q2: Q2.c
	gcc -o Q2 Q2.c

Q3: Q3Swap.c
	gcc -o Q3 Q3Swap.c

Q4: Q4StrRev.c
	gcc -o Q4 Q4StrRev.c

Q5: Q5BinarySearch.c
	gcc -o Q5 Q5BinarySearch.c