all: Q1 Q2a Q2b Q2cStack Q2cQueue Q3 Q5 Sort_CommandLineInput

Q1: Q1DynamicMemAllocation.c
	gcc -o Q1 Q1DynamicMemAllocation.c

Q2a: Q2aLinkedList.c
	gcc -o Q2a Q2aLinkedList.c

Q2b: Q2DLL.c
	gcc -o Q2b Q2DLL.c

Q2cStack: Q2Stack.c
	gcc -o Q2cStack Q2Stack.c

Q2cQueue: Q2Queue.c
	gcc -o Q2cQueue Q2Queue.c

Q3: Q3PointerToFunc.c
	gcc -o Q3 Q3PointerToFunc.c

Q5: Q5Sort.c
	gcc -o Q5 Q5Sort.c

Sort_CommandLineInput: Q5SortCommandLineInput.c
	gcc -o Sort_CommandLineInput Q5SortCommandLineInput.c