all: AVL BST Sort Sort_CommandLineInput

AVL: Q3AVL.c
	gcc -o AVL Q3AVL.c

BST: Q3BST.c
	gcc -o BST Q3BST.c

Sort: Q4Sort.c
	gcc -o Sort Q4Sort.c

Sort_CommandLineInput: Q4SortCommandLineInput.c
	gcc -o Sort_CommandLineInput Q4SortCommandLineInput.c